name: build

# This workflow installs the package and all dependencies from the
# ./environment.yml file on ubuntu and windows OS, calls 'setup.py test'
# and submits the resulting coverage report to coveralls.
# Runs on daily, on push and pull requests.

# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    name: Build py${{ matrix.python-version }} @ ${{ matrix.os }} 🐍
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.6', '3.7']
        os: ["ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: ./environment.yml
          activate-environment: ismn # must match with name: in yml (if name is set)
          auto-activate-base: false
      - name: Print environment infos
        shell: bash -l {0}
        run: |
          conda info -a
          conda list
          pip list
          which pip
          which python
      - name: Install package and test
        shell: bash -l {0}
        run: |
          python setup.py install
          python setup.py test
      - name: Upload Coverage
        shell: bash -l {0}
        run: |
          pip install coveralls && coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
  coveralls:
    name: Submit Coveralls 👚
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls && coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}